<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-28T13:58:06+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyACAY5pEoDnnZAB5m3rcgqFEJI8vy2ivuE',
        ],
    ],
];
